plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
    id 'java'
    id 'com.github.davidmc24.gradle.plugin.avro' version '1.9.1'
}


repositories {
    mavenCentral()
    // Confluent 전용 저장소 추가
    maven { url "https://packages.confluent.io/maven/" }
}


// [해결] 실행 파일(BootJar)은 만들지 말고, 일반 라이브러리(Jar)만 만든다.
bootJar { enabled = false }
jar { enabled = true }


dependencies {
    implementation project(':common')

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // payment/infra에 JPA Repository가 있으면 필요
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // payment/representation에 Controller가 있으면 필요
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter'

    implementation "org.springframework.kafka:spring-kafka"

    // 1. Confluent Kafka Avro Serializer (여기에 KafkaAvroDeserializer가 포함됨)
    implementation 'io.confluent:kafka-avro-serializer:7.6.0'

    // 2. Apache Avro (Avro 스키마 및 객체 처리를 위해 필요)
    implementation 'org.apache.avro:avro:1.11.3'

    // 보통 같이 필요 (스키마 레지스트리 사용 시)
    implementation "io.confluent:kafka-schema-registry-client:7.6.1"


    // 1. Retrofit Core (retrofit2.Retrofit 관련)
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'

    // 2. Jackson Converter (retrofit2.converter.jackson... 관련)
    // Retrofit이 응답받은 JSON을 자바 객체로 변환할 때 Jackson을 쓰게 해줍니다.
    implementation 'com.squareup.retrofit2:converter-jackson:2.9.0'

    // 3. OkHttp Client (okhttp3... 관련)
    // Retrofit은 내부적으로 OkHttp를 사용합니다.
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'

}