plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5' apply false
    id 'io.spring.dependency-management' version '1.1.6' apply false
}


allprojects {
    repositories {
        mavenCentral()
        maven { url "https://packages.confluent.io/maven/" }
    }
}




subprojects {
    // ✅ 이게 있어야 testImplementation이 생김
    apply plugin: 'java-library'

    apply plugin: 'io.spring.dependency-management'

    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    repositories {
        mavenCentral()
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:3.3.5"
        }
    }

    dependencies {
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }



}


configure([project(':notification'), project(':live')]) {
    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-data-redis'
        implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'

    }
}

configure([project(':payment')]) {
    dependencies {
        implementation 'org.springframework.kafka:spring-kafka'

    }
}


configure([project(':report-batch')]) {
    dependencies {
        runtimeOnly 'com.h2database:h2'
        runtimeOnly 'org.postgresql:postgresql'
        implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
        implementation 'com.fasterxml.jackson.core:jackson-core:2.17.2'

    }
}

