plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5' apply false
    id 'io.spring.dependency-management' version '1.1.6' apply false
}

allprojects {
    repositories {
        mavenCentral()
    }
}

subprojects {
    // ✅ 이게 있어야 testImplementation이 생김
    apply plugin: 'java-library'

    apply plugin: 'io.spring.dependency-management'

    repositories {
        mavenCentral()
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:3.3.5"
        }
    }

    dependencies {
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}

