server:
  port: 8080


spring:
  profiles:
    default: local
  application:
    name: ecommerce



# 기능 토글(중요): 배치/다른 실행 모듈에서 설정 없어도 안 터지게
app:
  kafka:
    enabled: true
  redis:
    enabled: true
  mongo:
    enabled: true
